spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/purchases
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level %logger - %msg%n"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
